"""
Case service — orchestrates AI calls for case creation, chat, plans, and documents.
"""

from sqlalchemy.orm import Session

from app.models.case import Case
from app.models.case_question import CaseQuestion
from app.models.action_plan import ActionPlan
from app.models.document import Document
from app.schemas.case import ChatResponse
from app.ai.classifier import classify_issue
from app.ai.rag.retriever import retrieve_legal_context
from app.ai.rag.generator import generate_response


def classify_and_create_case(db: Session, user_id: str, initial_issue: str) -> Case:
    """
    Create a new case.

    1. Calls the AI classifier to determine the legal domain and issue.
    2. Persists the Case row.
    3. Stores the initial user message as the first CaseQuestion.
    """
    classification = classify_issue(initial_issue)

    case = Case(
        user_id=user_id,
        domain=classification.get("domain"),
        issue=classification.get("issue"),
        status="new",
        summary=initial_issue,
    )
    db.add(case)
    db.commit()
    db.refresh(case)

    # Store the initial issue as the first message
    first_msg = CaseQuestion(case_id=case.id, question=initial_issue, role="user")
    db.add(first_msg)
    db.commit()

    return case


def handle_chat(db: Session, case: Case, message: str) -> ChatResponse:
    """
    Handle a single chat turn:

    1. Retrieve relevant legal context via RAG.
    2. Gather conversation history.
    3. Generate an AI response grounded in retrieved sources.
    """
    # 1. Retrieve legal context
    context_chunks = retrieve_legal_context(
        query=message,
        domain=case.domain or "",
        db=db,
    )

    # 2. Gather conversation history
    history = (
        db.query(CaseQuestion)
        .filter(CaseQuestion.case_id == case.id)
        .order_by(CaseQuestion.timestamp)
        .all()
    )
    history_dicts = [
        {"role": q.role, "content": q.question} for q in history
    ]

    # 3. Generate response
    ai_text = generate_response(
        query=message,
        context=context_chunks,
        case_history=history_dicts,
    )

    # Extract source references from context
    sources = [
        {"title": c.get("title", ""), "source_url": c.get("source_url", "")}
        for c in context_chunks
    ]

    return ChatResponse(
        response=ai_text,
        sources=sources,
        follow_up_questions=[],
    )


def generate_action_plan(db: Session, case: Case) -> ActionPlan:
    """
    Generate a step-by-step action plan for a case.

    This is a stub that returns a hardcoded plan matching the API contract.
    The AI teammate should replace the stub logic with an actual LLM call.
    """
    # TODO: Replace with LLM-generated plan based on case context
    stub_steps = [
        {
            "step": 1,
            "title": "Gather all relevant documents and evidence.",
            "description": "Collect contracts, receipts, communications, and any other supporting material.",
        },
        {
            "step": 2,
            "title": "Review the applicable legal provisions.",
            "description": "Understand the relevant laws and your rights in this situation.",
        },
        {
            "step": 3,
            "title": "Send a formal notice to the other party.",
            "description": "Draft and send a legal notice clearly stating your grievance and the remedy sought.",
        },
        {
            "step": 4,
            "title": "File a complaint with the appropriate authority.",
            "description": "If the notice is ignored, escalate by filing a formal complaint.",
        },
        {
            "step": 5,
            "title": "Seek professional legal assistance if needed.",
            "description": "Consult a lawyer or legal-aid centre for complex matters.",
        },
    ]

    plan = ActionPlan(
        case_id=case.id,
        steps=stub_steps,
        status="generated",
    )
    db.add(plan)
    db.commit()
    db.refresh(plan)
    return plan


def generate_document_draft(db: Session, case: Case) -> Document:
    """
    Generate a legal document draft for a case.

    This is a stub that returns a placeholder document.
    The AI teammate should replace this with an LLM-generated draft.
    """
    # TODO: Replace with LLM-generated document based on case context & evidence
    content = (
        f"DRAFT LEGAL NOTICE\n"
        f"==================\n\n"
        f"Subject: {case.issue or 'Legal Matter'}\n"
        f"Domain: {case.domain or 'General'}\n\n"
        f"Dear Sir/Madam,\n\n"
        f"This notice is being sent regarding the following matter:\n\n"
        f"{case.summary or 'No description provided.'}\n\n"
        f"[This is a draft generated by Nyaya Saathi. "
        f"Please review carefully and consult a legal professional before use.]\n\n"
        f"Yours faithfully,\n"
        f"[Your Name]"
    )

    doc = Document(
        case_id=case.id,
        doc_type="legal_notice",
        content=content,
    )
    db.add(doc)
    db.commit()
    db.refresh(doc)
    return doc
